safe: true
permalink: pretty
markdown: kramdown

title: Open Diversity Data New Zealand
author: Double Union & Brenda Wallace
description:
    List of companies who have released data about their employee diversity.
url: http://opendiversitydata.org.nz
repo: https://github.com/br3nda/opendiversitydata
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
